### ISSUE TITLE
Première version (réduite) de la librairie gtftk C

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#1]
Voilà une première version de cette librairie revue et corrigée. Deux fonctions sont disponibles :
- **loadGTF**(char *gtf_file) : **GTF_DATA \***
gtf_file est le nom d'un fichier gtf (ou gtf.gz) avec son chemin absolu (ex : /data/gtf/Homo_sapiens.GRCh38.87.chr.gtf.gz)
Cette fonction retourne un pointeur sur une structure GTF_DATA contenant :

     - **int size** : nombre de lignes dans le GTF
     - **GTF_ROW \*\*data** : tableau des lignes

Cette structure sera la représentation en mémoire d'un fichier GTF et sera fournie en entrée de toutes les futures fonctions.

- **select_by_key**(GTF_DATA *gtf_data, char *key, char *value, int not) : **GTF_DATA \***

    - gtf_data est un objet obtenu après appel de la fonction précédente
    - key est un nom de colonne ou d'attribut (feature, gene_name ...)
    - value est la liste des valeurs recherchées (séparées par des ",")
    - not vaut 1 pour faire une requête négative

Une fois n'est pas coutume, il y a **beaucoup** de commentaires dans les fichiers sources. Je vous invite donc à les lire goulûment ...
Pour compiler la bête (sous linux), rien de plus facile. Il suffit de se placer à la racine du projet (là où il y a libgtftk.c) et de taper : 
`gcc -I. -O3 -Wall -fmessage-length=0 -fPIC -MMD -MP -shared -o libgtftk.so  command/load_gtf.c command/select_by_key.c  column.c gtf_reader.c libgtftk.c -lz`

J'attends vos commentaire enthousiastes ...

**Comment by dputhier** [comment]
Je suis en train de tester. J'ai l'impression d'avoir un soucis quand j'essaie d'accéder aux valeurs d'un ligne. Visiblement, quand j'accède à une valeur numérique (le start par exemple), je reçois :  '}' .
Peut-être est-ce lié au fait qu'un ligne n'est plus un simple tableau de pointeurs vers des *char mais un tableau de pointeurs vers des *char ou des int. Tu peux préciser ?

from gtftk.gtf_interface import GTF
from  gtftk.utils import get_example_file
a = get_example_file()[0]
gtf =  GTF._dll.load_GTF(a)
gtf.contents.size # 70
row = gtf.contents.data.contents.contents.field

gtf.contents.data.contents.contents.field[0] # 'chr1'
gtf.contents.data.contents.contents.field[1] # 'gtftk'
gtf.contents.data.contents.contents.field[2] # 'gene'
gtf.contents.data.contents.contents.field[3] #  '}' NOT GOOD
gtf.contents.data.contents.contents.field[4] # NOT GOOD '\x8a'

**Comment by fafa13** [comment]
En effet, une ligne contient maintenant un tableau de pointeurs sur des void : 
```
typedef struct
GTF_ROW {
	// a pointer on the 9 values of a GTF file row
	void **data;

	// the rank number of the row in the GTF file
	int rank;
} GTF_ROW;

```
Avant, c'était sur des char.
Est-ce que c'est gérable en python d'avoir différents types de pointeurs dans le même tableau ?
Car maintenant, data contient 9 pointeurs qui sont, dans l'ordre :


    - char * (seqid)
    - char * (source)
    - char * (feature)
    - int * (start)
    - int * (end)
    - float * (score)
    - char * (strand)
    - int * (phase)
    - ATTRIBUTES * (attributes)

**Comment by dputhier** [comment]
Oui, tu m'en avais parlé... Désolé. Je vais chercher un peu et, si je ne trouve rien, poster sur stackoverflow. Mais c'est effectivement plus logique que ce soit typé.
A+

**Comment by fafa13** [comment]
Une solution est que je fasse une petite fonction de conversion d'un GTF_ROW en GTF_ROW_CHAR avec que des char *

**Comment by dputhier** [comment]
yeps, ca simplifierait l'utilisation. Pour l'instant je n'ai pas de solution mais j'aurais bien aimé réussir à implanter la version avec un array de pointeurs mixtes.

**Comment by dputhier** [comment]
It's seems it is feasible with some pointer arithmetic.  There is something I don't understand. Maybe you could help me.

The problem is that I have to go """ctypes.sizeof(ctypes.c_void_p) * 2""" to get to the  next result when going along the array of pointers. It seems weird to me. Would you do it like this ? @fafa13 could you comment please ?

     
     #### Let's call the library's load function
     from gtftk.utils import get_example_file
     a = get_example_file()[0]
     gtf = gtftk_so.load_GTF(a)

     #### Let's retrieve the pointer to the first ROW object
     row_ptr = gtf.contents.data[0].contents.data.contents.value

     #### Let's retrieve the chromosome
     row_ptr = gtf.contents.data.contents.contents.data.contents.value
     chr =ctypes.cast(row_ptr, ctypes.c_char_p).value
     chr # 'chr1', as expected

     #### Let's retrieve the source
     #### The idea is to jump to the next pointer that should point to the c_char_p
     #### What is strange is that I have to go """ctypes.sizeof(ctypes.c_void_p) * 2""" to get the      expected result. 
     #### If I don't multiply by 2 I get an empty string
     row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2
     src =ctypes.cast(row_ptr, ctypes.c_char_p).value
     src # 'gtftk' as expected.


     # Let's retrieve the feature type
     row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2 #still with *2
     ft_type =ctypes.cast(row_ptr, ctypes.c_char_p).value
     ft_type # 'gene' as expected.

**Comment by fafa13** [comment]
Could you please print the value of "ctypes.sizeof(ctypes.c_char_p)" ?
In C with 64 bits computers, this value is 8.

**Comment by dputhier** [comment]
ctypes.sizeof(ctypes.c_char_p)
8

**Comment by fafa13** [comment]
Can you print the value of row_ptr, at the beginning and after each increment operation ?

**Comment by dputhier** [comment]
In [32]: row_ptr = gtf.contents.data.contents.contents.data.contents.value

In [33]: row_ptr 
Out[33]: 4424444688

In [34]: row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2

In [35]: row_ptr 
Out[35]: 4424444704

In [36]: row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2

In [37]: row_ptr 
Out[37]: 4424444720

In [38]: row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2

In [39]: row_ptr 
Out[39]: 4424444736

In [40]: row_ptr += ctypes.sizeof(ctypes.c_char_p) * 2

In [41]: row_ptr 
Out[41]: 4424444752

**Comment by fafa13** [comment]
Difficile de comprendre pourquoi les pointeurs sont passés à python avec une taille de 128 bits. Ils ont peut être prévu large pour l'avenir ...
De toute façon, je suis d'accord avec toi, ça va faire du code python très dégueu, pire que le C !
Je pense qu'il vaut mieux que je fasse une fonction de conversion, que tu utiliseras à la fin du process sur ton jeu de données final. 
On voit ça la semaine prochaine !

**Comment by dputhier** [comment]
OK.

**Comment by dputhier** [comment]
J'ai finalement (après un plongeon dans la piscine) réussi à en écrire une version simplifiée, beaucoup plus satisfaisante et qui fonctionne.  Par contre il ya quelques cast à faire coté Python. Du coup il faudra voir au niveau de la vitesse.

from ctypes import cast
from ctypes import c_char_p
from ctypes import c_int
from ctypes import c_float
from ctypes import POINTER

class _ATTRIBUTE(ctypes.Structure):
    _fields_ = [("c_key", c_char_p),
                ("c_value", c_char_p)]


class _ATTRIBUTES(ctypes.Structure):
    _fields_ = [("c_attr", POINTER(POINTER(_ATTRIBUTE))),
                ("c_nb", c_int)]

from gtftk.gtf_interface import GTF
from gtftk.utils import get_example_file
#a = get_example_file()[0]
a = "gtftk/Homo_sapiens.GRCh38.87.chr.gtf"
gtf = gtftk_so.load_GTF(a)

row_ptr = gtf.contents.data.contents.contents.data
chr = cast(row_ptr[0], c_char_p).value
src = cast(row_ptr[1], c_char_p).value
ft_type = cast(row_ptr[2], c_char_p).value
start = cast(row_ptr[3], POINTER(c_int)).contents.value
end = cast(row_ptr[4], POINTER(c_int)).contents.value
score = cast(row_ptr[5], POINTER(c_float)).contents.value
strand = cast(row_ptr[6], c_char_p).value
frame = cast(row_ptr[7], POINTER(c_int)).contents.value
attr = cast(row_ptr[8], POINTER(_ATTRIBUTES))
attr_list = attr.contents.c_attr[0:attr.contents.c_nb]
print([x.contents.c_value for x in attr_list])
print([x.contents.c_key for x in attr_list])

['ENSG00000223972', '5', 'DDX11L1', 'havana', 'transcribed_unprocessed_pseudogene', 'OTTHUMG00000000961', '2']
['gene_id', 'gene_version', 'gene_name', 'gene_source', 'gene_biotype', 'havana_gene', 'havana_gene_version']

**Comment by dputhier** [comment]
Everything seems to be OK on that side. Closing the 'issue'.
