### ISSUE TITLE
write_function

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#10]
I think that in addition to a file_path, the write function could accept a 'add_chr' arg to indicate whether one should prefix all lines with 'chr'. This can be helpful when dealing with ensembl file.

A user fed up with sed 's/^/chr/'...

**Comment by dputhier** [comment]
:)

**Comment by fafa13** [comment]
The print_gtf_data function has now a new argument called add_chr :

`void print_gtf_data(GTF_DATA *gtf_data, char *output, int add_chr);
`

If add_chr is 1, the function prints "chr" at the beginning of the lines. It does not check whether the lines already begins with "chr".

**Comment by dputhier** [comment]
OK. I will maybe propose it as a command-wise argument so that any command can benefit from this.
