### ISSUE TITLE
New library version !!!

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#15]
A new version of the library is available in **develop_3.0** branch. A lot of internal changes and also in the definition of the data types :

```
GTF_DATA
 int size
 GTF_ROW *data

GTF_ROW
 char **fields
 int nb_attributes
 char **key, **value
 int rank
```

As you can see, GTF_DATA contains 2 fields :
- size : the number of rows in the GTF
- data : a single pointer on an array of GTF_ROWs

GTF_ROW contains :
- fields : a table of 8 pointers on strings (the 8 first columns values)
- nb_attributes : the number of attributes in the 9th field
- key, value : 2 tables of strings (their size is nb_attributes)
- rank : the row number in the GTF file

A new function appears : **free_gtf_data(GTF_DATA \*gtf_data)**
This function **must** be called to release the memory used by a GTF_DATA.

**Comment by dputhier** [comment]
Je pense que la fonction print_gtf_data pose un problème. Quand je parcours les objets ils contiennent des start/end/frame qui sont comme attendus. Quand j'utilise print_gtf_data j'obtient des coordonnées délirantes (en millions quand dans l'exemple c'est entre 0 et 400). Ce serait pas mal d'en profiter pour lui ajouter un nom de fichier (ou - si stdout).
Ciao

**Comment by fafa13** [comment]
C'est corrigé et sur le git.

Le nom de fichier, c'est pour bientôt !

**Comment by fafa13** [comment]
C'est OK pour le nom de fichier en deuxième paramètre.

**Comment by dputhier** [comment]
Ca fonctionne.
