### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#17]
Sometimes it is related to more severe issues...

tftk/src/libgtftk/command/extract_data.c:132:18: warning: implicit declaration of function 'is_in_attrs' is invalid in C99 [-Wimplicit-function-declaration]
                        else if ((n = is_in_attrs(&gtf_data->data[k], ret->column_name[i])) != -1)
                                      ^
1 warning generated.

**Comment by fafa13** [comment]
I have just fixed this one. It's only a warning.
