### ISSUE TITLE
select_by_key malloc: *** error for object 0x1f4a54fd8: incorrect checksum for freed object - object was probably modified after being freed.

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#2]
The select_by_key function works with a simple dataset (although I got also some segfault) but goes into error with a large file (error observed with  Homo_sapiens, Otolemur_garnettii, Sus scrofa)

First with the simple dataset

	In [3]: from gtftk.gtf_interface import GTF

	In [4]: from gtftk.utils import get_example_file

	In [5]: gtf = GTF("gtftk/gtftk/data/simple/simple.gtf")

	In [6]: gtf.load()

	In [7]: gtf
	Out[7]: 

	- A GTF object containing 70 lines:
	- File connection: gtftk/gtftk/data/simple/simple.gtf

	chr1	gtftk	gene	125	138	-1.0	+	-1	gene_id "G0001";
	chr1	gtftk	transcript	125	138	-1.0	+	-1	gene_id "G0001"; transcript_id "G0001T002";
	chr1	gtftk	exon	125	138	-1.0	+	-1	gene_id "G0001"; transcript_id "G0001T002"; exon_id "G0001T002E001";
	chr1	gtftk	CDS	125	130	-1.0	+	-1	gene_id "G0001"; transcript_id "G0001T002"; ccds_id "CDS_G0001T002";
	chr1	gtftk	transcript	125	138	-1.0	+	-1	gene_id "G0001"; transcript_id "G0001T001";
	chr1	gtftk	exon	125	138	-1.0	+	-1	gene_id "G0001"; transcript_id "G0001T001"; exon_id "G0001T001E001";

	In [8]: len(gtf)
	Out[8]: 70

	In [5]: gtf.select_by_key("feature","gene")
	Out[5]: 

	- A GTF object containing 10 lines:
	- File connection: gtftk/gtftk/data/simple/simple.gtf

	chr1	gtftk	gene	125	138	-1.0	+	-1	gene_id "G0001";
	chr1	gtftk	gene	180	189	-1.0	+	-1	gene_id "G0002";
	chr1	gtftk	gene	50	61	-1.0	-	-1	gene_id "G0003";
	chr1	gtftk	gene	65	76	-1.0	+	-1	gene_id "G0004";
	chr1	gtftk	gene	33	47	-1.0	-	-1	gene_id "G0005";
	chr1	gtftk	gene	22	35	-1.0	-	-1	gene_id "G0006";

Now with Sus Scrofa.

	In [9]: gtf = GTF("gtftk/Sus_scrofa.Sscrofa10.2.87.chr.gtf.gz")

	In [10]: gtf.load()

	In [11]: len(gtf)
	Out[11]: 537898

	In [12]: gtf
	Out[12]: 

	- A GTF object containing 537898 lines:
	- File connection: gtftk/Sus_scrofa.Sscrofa10.2.87.chr.gtf.gz

	1	ensembl	gene	159167	166508	-1.0	-	-1	gene_id "ENSSSCG00000030218"; gene_version "1"; gene_source "ensembl"; gene_biotype "protein_coding";
	1	ensembl	transcript	159167	166508	-1.0	-	-1	gene_id "ENSSSCG00000030218"; gene_version "1"; transcript_id "ENSSSCT00000026690"; transcript_version "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
	1	ensembl	exon	166481	166508	-1.0	-	-1	gene_id "ENSSSCG00000030218"; gene_version "1"; transcript_id "ENSSSCT00000026690"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSSSCE00000218470"; exon_version "1";
	1	ensembl	CDS	166481	166508	-1.0	-	0	gene_id "ENSSSCG00000030218"; gene_version "1"; transcript_id "ENSSSCT00000026690"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; protein_id "ENSSSCP00000020937"; protein_version "1";
	1	ensembl	start_codon	166506	166508	-1.0	-	0	gene_id "ENSSSCG00000030218"; gene_version "1"; transcript_id "ENSSSCT00000026690"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding";
	1	ensembl	exon	163896	164592	-1.0	-	-1	gene_id "ENSSSCG00000030218"; gene_version "1"; transcript_id "ENSSSCT00000026690"; transcript_version "1"; exon_number "2"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSSSCE00000176199"; exon_version "1";

	In [13]: gtf.select_by_key("feature", "gene")
	python(38484,0x7fff77b36000) malloc: *** error for object 0x105c9f7e8: incorrect checksum for freed object - object was probably modified after being freed.
	*** set a breakpoint in malloc_error_break to debug
	Abort trap: 6

Error is :

python(38484,0x7fff77b36000) malloc: *** error for object 0x105c9f7e8: incorrect checksum for freed object - object was probably modified after being freed.
	*** set a breakpoint in malloc_error_break to debug
	Abort trap: 6

**Comment by dputhier** [comment]
I tried to change the py_select_by_key function. I modified it so that it returns nothing, it just call the dll. I get an alternative error which may help us to debug maybe...

	In [1]: from gtftk.gtf_interface import GTF

	In [2]: gtf = GTF("gtftk/gtftk/data/simple/simple.gtf")

	In [3]: gtf.load()

	In [4]: gtf.select_by_key("feature", "gene")

	In [5]: gtf = GTF("gtftk/Sus_scrofa.Sscrofa10.2.87.chr.gtf.gz")

	In [6]: gtf.load()

	In [7]: gtf.select_by_key("feature","gene")

	Fatal Python error: GC object already tracked
	Abort trap: 6

**Comment by fafa13** [comment]
Corrected, thanks to OSX !

**Comment by dputhier** [comment]
Let's burn all our PCs and try to repair the macs we burned few weeks ago. :)
Seems to be working now !
