### ISSUE TITLE
big update

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#20]
Hello,
a lot of changes in this push :
- the column model lose some weight. It is not anymore an object-like structure. As you don't use it, you should have nothing to change in the python side.
- there is a **free_raw_data** function to release memory allocated to a RAW_DATA after a call to extract_data
- **extract data** has 2 more parameters : 
`RAW_DATA *extract_data(GTF_DATA *gtf_data, char *key, int base, int uniq);`
base : 0 or 1 (for the start value)
uniq : doesn't work for now but in the future, it should allow to remove duplicate rows in the results
- **print_gtf_data** and **print_raw_data** have an output parameter (a string : "-" for standard output or a string for a file name)

Now, you have to adapt the python code ... look in **libgtftk.h** for the modifications of structures and functions parameters !

**Comment by dputhier** [comment]
Nice. But the problem related to the index is still remaining.

     a = gtf.select_by_key("feature", "transcript").select_by_key("feature", "transcript")
    Segmentation fault: 11

So I'm wondering whether I should wait for a more bug free version as it takes time to rewrite the interface. Tell me.
Bye

**Comment by fafa13** [comment]
I think that you continue to rewrite the interface as the API should not 
change now, even if there remains some bugs to fix.
