### ISSUE TITLE
select_by_key with invert_match throw segfault if value does not exist

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#22]
This error is observed in the develop branch. Not tested in develop_3.0 (as issue #20 is not fixed at the moment). 
When using select_by_key with invert_match if value does not correspond to any transcript, a segfault is produced:

      from  gtftk.utils import get_example_file
      from gtftk.gtf_interface import GTF
      a_file = get_example_file()[0]
      gtf = GTF(a_file)
      #OK, IDs exist in the dataset 
      gtf.select_by_key("transcript_id", "G0001T001,G0001T002", invert_match=True) 
     # OK, one of both IDs exist in the dataset.
     gtf.select_by_key("transcript_id", "G0001T001,a", invert_match=True)
     #ERROR. a and b IDs are not part of the dataset.
     gtf.select_by_key("transcript_id", "a,b", invert_match=True)
     Segmentation fault: 11

**Comment by dputhier** [comment]
Still true in 3.0.

**Comment by fafa13** [comment]
Works on 3.2

**Comment by dputhier** [comment]
Think about deleting the stderr output in select_by_key.c (l 178).

fprintf(stderr, "size = %d\n", ret->size);
