### ISSUE TITLE
Select_by_key: not operator when key or value does not exists

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#26]
There seems to be a problem with the not operator when key or value does not exist. Should return a 0 length GTF_DATA not a segfault.

from  gtftk.utils import get_example_file
from gtftk.gtf_interface import GTF
from gtftk.utils import TAB
a_file = get_example_file()[0]
gtf = GTF(a_file, check_ensembl_format=False)
gtf.select_by_key("bla", "bla", invert_match=True) # Segfault

**Comment by fafa13** [comment]
Are you sure that when key or value does not exist, the return must be a 0 length GTF_DATA ? When the value or the key does not exist, I think that the return should be the initial GTF_DATA.

**Comment by dputhier** [comment]
You are right. The input GTF should be return.

**Comment by dputhier** [comment]
Ideally, we should return a GTFtkError. But this is probably another story/version.
Best

**Comment by fafa13** [comment]
Fixed. Now returns the input GTF.
