### ISSUE TITLE
Error when freeing GTF_DATA is fixed + get_*_list functions

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#28]
Hi,
the memory error that occurred when GTF_DATA was freed is fixed in all functions that return a GTF_DATA. 
Additional information is added in SEQUENCE structures returned by get_sequences() function. Now, SEQUENCE structure is defined as :

```
typedef struct SEQUENCE {
	char *header, *sequence, strand, *seqid, *gene_id, *transcript_id, *gene_name, *gene_biotype;
	int start, end;
	FEATURES *features;
} SEQUENCE;

```
In this push, I finished to implements the get_*_list functions that were in stand-bye :
- **get_feature_list**(GTF_DATA *gtf_data) : returns the list of features in a GTF_DATA
- **get_seqid_list**(GTF_DATA *gtf_data) : returns the list of seqid (chromosomes) in a GTF_DATA
- **get_attributes_list**(GTF_DATA *gtf_data) : returns the list of attributes in a GTF_DATA
- **get_attribute_values_list**(GTF_DATA *gtf_data, char *attribute) : returns the list of values in a GTF_DATA for a given attribute (gene_name, gene_biotype ...)

All those functions returns a **TTEXT** pointer. TTEXT is defined as :

```
typedef struct TTEXT {
	int size;
	char ***data;
} TTEXT;
```
This structure is used to store a list of tabulated rows, that's why data is a 3* pointer :
- data[i] is a pointer (char **) on a table of strings, that is the list of words in the row i
- data[i][j] (char *) is the word j in the column i

Have fun with that and let me know if works fine !

**Comment by dputhier** [comment]
Hi Fa,
Still have problem with freeing. Maybe we should get some time together to have a look. I'm on 0a4f368297587f3dde35ad9bc70dcf1aa9056f8c.
Ciao

**Comment by dputhier** [comment]
The error happens with select_by_genomic_location, select_by_nb_exons and select_by_tx_size. Not with all other function tested.
Ciao

**Comment by dputhier** [comment]
Does the select_by_genomic_location works for you ? It seems that the segfault I got is related to the function call itself not to the freeing.
Best
