### ISSUE TITLE
develop_3.1 branch

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#29]
I have created a new branch (develop_3.1) in which the **data** member of GTF_DATA structure is a **GTF_ROW \*\*** (instead of GTF_ROW *). I did that to allow the insertion of rows in a GTF_DATA. This will be used in the coming soon convert_to_ensembl function to add gene and transcript rows.
However, it's a big change and I hope all is still working fine. Could you test it soon and tell me if the speed is not too much impacted ?
I have also added a new member called **next** in the GTF_ROW structure. This is a pointer on the next row because **data** is now a table of pointers and also a linked-list at the same time. It is useless on the python side. You can just ignore it for the moment.

**Comment by dputhier** [comment]
Look at that 💯 .

![image](https://user-images.githubusercontent.com/1831198/26926869-b34aa528-4c4f-11e7-89ea-7711a8bda48d.png)

**Comment by Nicolas-Fernandez** [comment]
✓ get_attr_list_3
✓ clean

259 tests, 0 failures
make[1]: Leaving directory '/home/eleusis/gtftk_dev'
(gtftk_dev) eleusis@Eleusis-MSI:~/gtftk_dev$

:1st_place_medal:  Denis / Fafa / Guillaume !
