### ISSUE TITLE
The 'uniq' argument to extract_data has disappeared in 3.1

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#30]
We just have to decide whether this should be taken in charge on the Python side.

**Comment by fafa13** [comment]
What should be the behavior of this command :
- each line must be unique in the output ?
or
- two adjacent lines must be different (like the uniq command in unix) ?

**Comment by dputhier** [comment]
Interesting question. I was thinking of a non redondant list that would append the first occurence of a line and discard any additional occurrence, while preserving the sorting and allowing to discard undefined values ".".  The idea is for instance to get the non redondant list of transcript_id, gene_id, chromosomes, features or any encountered key.

**Comment by fafa13** [comment]
The uniq parameter is back in 3.3 branch. This parameter is boolean (0 or 1). If 1, the result is made of non redundant rows. Note that for what you asked in the previous comment, you should have a look at those functions :
```
TTEXT *get_feature_list(GTF_DATA *gtf_data);
TTEXT *get_seqid_list(GTF_DATA *gtf_data);
TTEXT *get_attribute_list(GTF_DATA *gtf_data);
TTEXT *get_attribute_values_list(GTF_DATA *gtf_data, char *attribute);

```
They return respectively the list of features, seqid (chromosomes), attributes and values of a given attribute in a structure called TTEXT :
```
typedef struct TTEXT {
	int size;
	char ***data;
} TTEXT;
```
This structure contains two columns of strings. The second column is the asked data and the first column is the amount. For example, if you want to get all the features in a GTF :
```
gtftk --gl feature Homo_sapiens.GRCh38.89.chr.gtf.gz
710166 : CDS
119 : Selenocysteine
1193694 : exon
143497 : five_prime_utr
58174 : gene
83231 : start_codon
74952 : stop_codon
136436 : three_prime_utr
199167 : transcript
```
Or all the attributes:
```
gtftk --gl attributes Homo_sapiens.GRCh38.89.chr.gtf.gz
gene_id
gene_version
gene_name
gene_source
gene_biotype
transcript_id
transcript_version
transcript_name
transcript_source
transcript_biotype
tag
transcript_support_level
exon_number
exon_id
exon_version
ccds_id
protein_id
protein_version
```
Or all the values of the gene_biotype attribute:
```
gtftk --gl attribute:gene_biotype Homo_sapiens.GRCh38.89.chr.gtf.gz
135 : 3prime_overlapping_ncRNA
203 : IG_C_gene
33 : IG_C_pseudogene
152 : IG_D_gene
76 : IG_J_gene
9 : IG_J_pseudogene
1168 : IG_V_gene
664 : IG_V_pseudogene
3 : IG_pseudogene
6 : Mt_rRNA
66 : Mt_tRNA
3278 : TEC
70 : TR_C_gene
16 : TR_D_gene
316 : TR_J_gene
12 : TR_J_pseudogene
838 : TR_V_gene
111 : TR_V_pseudogene
44814 : antisense
90 : bidirectional_promoter_lncRNA
57014 : lincRNA
3 : macro_lncRNA
5637 : miRNA
6636 : misc_RNA
9 : non_coding
1744 : polymorphic_pseudogene
32353 : processed_pseudogene
16541 : processed_transcript
2374390 : protein_coding
76 : pseudogene
1626 : rRNA
24 : ribozyme
15 : sRNA
3 : scRNA
147 : scaRNA
3602 : sense_intronic
1382 : sense_overlapping
5700 : snRNA
2853 : snoRNA
3358 : transcribed_processed_pseudogene
3403 : transcribed_unitary_pseudogene
16684 : transcribed_unprocessed_pseudogene
624 : unitary_pseudogene
13549 : unprocessed_pseudogene
3 : vaultRNA
```

**Comment by dputhier** [comment]
I just installed the 3.3 version. I got 199 failures out of 373 under OSX. It seems that it is frequently observed at program exit (free_gtf_data() ?).

      gtftk feature_size -i gtftk/data/simple/simple.gtf  -t mature_rna  -n transcript_id,gene_id | gtftk select_by_key -k feature -v transcript
     chr1	gtftk	transcript	125	138	.	+	.	gene_id "G0001"; transcript_id "G0001T002"; feat_size "14";
    ...
    ...
    chr1	gtftk	transcript	176	186	.	+	.	gene_id "G0010"; transcript_id "G0010T001"; feat_size "11";
   Segmentation fault: 11


The problem is for instance observed with select_by_key.
