### ISSUE TITLE
add_attributes

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#32]
Hello,
just to tell you that I have added the **add_attributes** function in the library. This function add a key/value pair attribute in a GTF from a tabulated file.
For example, let's say that we want to add the number of exons for each transcript in the GTF. We want, in all the "transcript" rows, a new attribute called "nb_exons". First we have to make a text file containing two columns : the transcript_id and the number of exons. Here is an excerpt of such a file:
```
ENST00000603175	1
ENST00000529131	6
ENST00000603176	1
ENST00000529132	3
ENST00000603177	3
ENST00000407221	11
ENST00000529133	5
```
Then, we can add this information as a new attribute by calling the **add_attributes** function like that:
```
gtf_data = add_attributes(gtf_data0, "transcript", "transcript_id", "nb_exons", "nb_exons.txt");
```

- _gtf_data0_ is the GTF_DATA obtained by a call to load_gtf function
- _transcript_ is used to tell that only the transcript lines must be annotated. This parameter can contain several feature column values separated by "," characters. In that case, all the lines that satisfy one of the values are annotated. This parameter is restricted to feature column values but could be extended to all the columns and attributes if needed
- _transcript_id_ is the name of the key that link the data in the GTF with the data in the tabulated file. Here, we have transcript ids in the tabulated file, so we must tell the function that _transcript_id_ is the linking key
- _nb_exons_ is just the name of the new attribute
- _nb_exons.txt_ is the tabulated file containing the new attribute values

The call to **add_attributes** clone the initial GTF_DATA so that it is not modified. If you don't need it anymore, don't forget to free it. Here is the result of the previous call:

```
1	havana	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2
"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; havana_gene "OTTHUMG00000000961"; havana_gene_version "2"; transcript_name
 "DDX11L1-002"; transcript_source "havana"; transcript_biotype "processed_transcript"; havana_transcript "OTTHUMT00000362751"; havana_transcript_version "1"; tag "basic"; 
transcript_support_level "1"; nb_exons "3";
```
As you can see, a beautiful "nb_exons" attribute is present at the end of the line.
This first implementation of the add_attributes function is limited to one attribute per file. We could enhance that by allowing several attributes to be in the text file, with the names of the attributes as the first row.

Now, I just need to write the reciprocal function (remove_attributes), write a few thousand comment lines and we can freeze a first release candidate version of the C library. The end is not so far ...

**Comment by dputhier** [comment]
Great news ! Will test it ASAP. This is in 3.1 I guess (?).

**Comment by fafa13** [comment]
Yes, it is only in 3.1

**Comment by dputhier** [comment]
Yet another motivation to go 3.1 and freeze !
