### ISSUE TITLE
add_attribute: a single char is deleted in the last line

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#34]
Testing, testing :).
The add_attribute function works like a charm. I found a little bug when testing the result. 

My testing file contains the following 2 columns (gene_ids and values for a novel key).

     G0003   0.2322\n
     G0004   0.999\n
     G0009   0.5555

Although everything is perfect for G0003 and G0004, the value for G0009 is 0.555 instead of 0.5555.
Best

**Comment by fafa13** [comment]
I think I fixed that a long time ago ...
