### ISSUE TITLE
add_attr: 2 times but not three...

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#35]
I encountered a problem with add_attr. I tried to join 3 set of attributes into GTF from the 'simple' dataset. There is no problem with the 2 first join. However upon the third join, there is a lot of instability. Sometimes it works sometimes it doesn't sometimes it works for some keys. Here are the three joined dataset. Changing the third with the second does not change the problem, still unstable results.
That one won't be easy :).

G0010	0,24
G0002	0,21
G0003	3,4
G0001	9,38
G0006	0,8
G0007	9,31
G0004	4,18
G0005	0,3
G0008	21,24
G0009	8,19

G0010	G0002,G0008
G0002	G0010,G0008
G0003	G0005,G0004
G0001	G0007,G0010
G0006	G0005,G0009
G0007	G0001,G0004
G0004	G0003,G0005
G0005	G0006,G0003
G0008	G0002,G0010
G0009	G0006,G0005

G0010	+,-
G0002	+,-
G0003	-,+
G0001	+,+
G0006	-,-
G0007	+,+
G0004	-,-
G0005	-,-
G0008	+,+
G0009	-,-

**Comment by fafa13** [comment]
Hi,
that works great for me, on the C side. Here is the C code I used to test :
```
gtf_data0 = load_GTF(comm->gtf_filename);
gtf_data = add_attributes(gtf_data0, "gene", "gene_id", "join1", "/home/fafa/workspaceC/gtftkc/src/gtftkc/join1.txt");
gtf_data1 = add_attributes(gtf_data, "gene", "gene_id", "join2", "/home/fafa/workspaceC/gtftkc/src/gtftkc/join2.txt");
gtf_data2 = add_attributes(gtf_data1, "gene", "gene_id", "join3", "/home/fafa/workspaceC/gtftkc/src/gtftkc/join3.txt");
print_gtf_data(gtf_data2, "-");
````
And here is the output, piped with a "grep join" (in my test, I annotate only the "gene" lines) :
```
chr1	gtftk	gene	125	138	.	+	.	gene_id "G0001"; join1 "9,38"; join2 "G0007,G0010"; join3 "+,+";
chr1	gtftk	gene	180	189	.	+	.	gene_id "G0002"; join1 "0,21"; join2 "G0010,G0008"; join3 "+,-";
chr1	gtftk	gene	50	61	.	-	.	gene_id "G0003"; join1 "3,4"; join2 "G0005,G0004"; join3 "-,+";
chr1	gtftk	gene	65	76	.	+	.	gene_id "G0004"; join1 "4,18"; join2 "G0003,G0005"; join3 "-,-";
chr1	gtftk	gene	33	47	.	-	.	gene_id "G0005"; join1 "0,3"; join2 "G0006,G0003"; join3 "-,-";
chr1	gtftk	gene	22	35	.	-	.	gene_id "G0006"; join1 "0,8"; join2 "G0005,G0009"; join3 "-,-";
chr1	gtftk	gene	107	116	.	+	.	gene_id "G0007"; join1 "9,31"; join2 "G0001,G0004"; join3 "+,+";
chr1	gtftk	gene	210	222	.	-	.	gene_id "G0008"; join1 "21,24"; join2 "G0002,G0010"; join3 "+,+";
chr1	gtftk	gene	3	14	.	-	.	gene_id "G0009"; join1 "8,19"; join2 "G0006,G0005"; join3 "-,-";
chr1	gtftk	gene	176	186	.	+	.	gene_id "G0010"; join1 "0,24"; join2 "G0002,G0008"; join3 "+,-";

```

**Comment by dputhier** [comment]
But don't you observe any instability in the result ? This is still the case for me...

**Comment by dputhier** [comment]
Could it be an OSX specific one ?

**Comment by fafa13** [comment]
For me, the result is always the same.
What do you call "instability" ? The results change, you have segfaults, ... ?

**Comment by dputhier** [comment]
No segfault. The last join (strand) just work from time to time.

**Comment by dputhier** [comment]
I will do more tests.

**Comment by dputhier** [comment]
It seems that it comes from somewhere in my code. The joining works fine when perform interactively in ipython:

	In [36]: for i in range(10):
	    ...:     print(a_gtf.add_attr_from_file(feat="gene",inputfile="join1.txt", key="gene_id", n
	    ...: ew_key="join1").add_attr_from_file(feat="gene",inputfile="join2.txt", key="gene_id", n
	    ...: ew_key="join2").add_attr_from_file(feat="gene",inputfile="join3.txt", key="gene_id", n
	    ...: ew_key="join3").select_by_key("feature","gene").get_attr_list())
	    ...:     
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']
	['gene_id', 'join1', 'join2', 'join3']

**Comment by dputhier** [comment]
I think its related to some strange behaviour somewhere with the garbage collector... Digging...

**Comment by dputhier** [comment]
OK. This one is really really weird and at the moment I can not find any nice solution. When performing several joins in cascade, we are creating several GTF objects. What happens is that the previous instances will be garbage collected. This is true in the example below (a fraction of the code which has strange behaviour) since the gtf variable is erased each time using gtf = gtf... :

    if not text_format:

        if len(gene_closest) > 0:

            message("JOIN1")
            gtf = gtf.add_attr_from_dict(feat="gene",
                                         key=identifier,
                                         a_dict=gene_closest,
                                         new_key="closest_gn"
                                         )
            gtf = gtf.add_attr_from_dict(feat="gene",
                                         key=identifier,
                                         a_dict=gene_closest_dist,
                                         new_key="closest_dist")

            if add_strands:
                message("JOIN3")
                gtf = gtf.add_attr_from_dict(feat="gene",
                                             key=identifier,
                                             a_dict=gene_closest_strand,
                                             new_key="closest_strand")





 Frequently, it happens that the system will use an address for the GTF_DATA that was previously used. In this case, the last join won't work. For instance, this first example works (the 'closest_strand' key is joined). The last created GTF_DATA got address that was not previously used (0x7fc3c5600000).

    $ gtftk get_example |  bedtools sort | gtftk closest_genes -n 2  -t gene -r gene -a -K /tmp/toto -V 2 2>&1 | perl -ne 'print if(/(closest_gn)|(created)|(Freing)/)'
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fc3c7354030, id=4437499600).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=10, file_name=-, ptr_addr=0x7fc3c7322f20, id=4437299792).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fc3c512c1c0, id=4437012368).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fc3c7354030, id=4437499600).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fc3c740ea50, id=4437499600).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fc3c512c1c0, id=4437012368).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fc3c5600000, id=4437012368).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fc3c740ea50, id=4437499600).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fc3c5600000, id=4437012368).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=10, file_name=-, ptr_addr=0x7fc3c7322f20, id=4437299792).
    ['gene_id', 'closest_gn', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'closest_strand', 'transcript_id', 'ccds_id', 'exon_id']
    chr1	gtftk	gene	3	14	.	-	.	gene_id "G0009"; closest_gn "G0006,G0005"; closest_dist "8,19"; closest_strand "-,-";
    chr1	gtftk	gene	22	35	.	-	.	gene_id "G0006"; closest_gn "G0005,G0009"; closest_dist "0,8"; closest_strand "-,-";
    chr1	gtftk	gene	33	47	.	-	.	gene_id "G0005"; closest_gn "G0006,G0003"; closest_dist "0,3"; closest_strand "-,-";
    chr1	gtftk	gene	50	61	.	-	.	gene_id "G0003"; closest_gn "G0005,G0004"; closest_dist "3,4"; closest_strand "-,+";
    chr1	gtftk	gene	65	76	.	+	.	gene_id "G0004"; closest_gn "G0003,G0005"; closest_dist "4,18"; closest_strand "-,-";
    chr1	gtftk	gene	107	116	.	+	.	gene_id "G0007"; closest_gn "G0001,G0004"; closest_dist "9,31"; closest_strand "+,+";
    chr1	gtftk	gene	125	138	.	+	.	gene_id "G0001"; closest_gn "G0007,G0010"; closest_dist "9,38"; closest_strand "+,+";
    chr1	gtftk	gene	176	186	.	+	.	gene_id "G0010"; closest_gn "G0002,G0008"; closest_dist "0,24"; closest_strand "+,-";
    chr1	gtftk	gene	180	189	.	+	.	gene_id "G0002"; closest_gn "G0010,G0008"; closest_dist "0,21"; closest_strand "+,-";
    chr1	gtftk	gene	210	222	.	-	.	gene_id "G0008"; closest_gn "G0002,G0010"; closest_dist "21,24"; closest_strand "+,+";
 

In contrast, this second example won't work (the 'closest_strand' key is not joined). The last created GTF_DATA got an already used address (that was previously used, 0x7fb04750e6e0).

    $ gtftk get_example |  bedtools sort | gtftk closest_genes -n 2  -t gene -r gene -a -K /tmp/toto -V 2 2>&1 | perl -ne 'print if(/(closest_gn)|(created)|(Freing)/)'
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fb047422120, id=4598140624).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=10, file_name=-, ptr_addr=0x7fb04744a970, id=4597940816).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fb04750e6e0, id=4597653392).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fb047422120, id=4598140624).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fb0463e3d20, id=4598140624).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fb04750e6e0, id=4597653392).
        |--- 10:27-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7fb04750e6e0, id=4597653392).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fb0463e3d20, id=4598140624).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7fb04750e6e0, id=4597653392).
        |--- 10:27-DEBUG-closest_genes : Freing (nb_lines=10, file_name=-, ptr_addr=0x7fb04744a970, id=4597940816).
    ['gene_id', 'closest_gn', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'transcript_id', 'ccds_id', 'exon_id']
    chr1    gtftk   gene    3   14  .   -   .   gene_id "G0009"; closest_gn "G0006,G0005"; closest_dist "8,19";
    chr1    gtftk   gene    22  35  .   -   .   gene_id "G0006"; closest_gn "G0005,G0009"; closest_dist "0,8";
    chr1    gtftk   gene    33  47  .   -   .   gene_id "G0005"; closest_gn "G0006,G0003"; closest_dist "0,3";
    chr1    gtftk   gene    50  61  .   -   .   gene_id "G0003"; closest_gn "G0005,G0004"; closest_dist "3,4";
    chr1    gtftk   gene    65  76  .   +   .   gene_id "G0004"; closest_gn "G0003,G0005"; closest_dist "4,18";
    chr1    gtftk   gene    107 116 .   +   .   gene_id "G0007"; closest_gn "G0001,G0004"; closest_dist "9,31";
    chr1    gtftk   gene    125 138 .   +   .   gene_id "G0001"; closest_gn "G0007,G0010"; closest_dist "9,38";
    chr1    gtftk   gene    176 186 .   +   .   gene_id "G0010"; closest_gn "G0002,G0008"; closest_dist "0,24";
    chr1    gtftk   gene    180 189 .   +   .   gene_id "G0002"; closest_gn "G0010,G0008"; closest_dist "0,21";
    chr1    gtftk   gene    210 222 .   -   .   gene_id "G0008"; closest_gn "G0002,G0010"; closest_dist "21,24";


It seems that the garbage collector is getting a little bit lost. The __del__ method of a GTF object is associated with the following code. 


    def __del__(self):

        if self._data != 0:
            self._message("Freing ")
            self._dll.free_gtf_data(self._data)
            self._data = 0


If the 'self._dll.free_gtf_data(self._data)' is commented, it will work. But this is clearly not satisfying... 

To be continued (but I don't have any idea at the moment).

**Comment by dputhier** [comment]
Just to remember... What is also weird is that the problem won't happen if I'm using different variable names such as gtf0, gtf1,gtf2... In this case, everything will be garbage collected at the end. So the last one will always contain the three sets of key/values...


    if not text_format:

        if len(gene_closest) > 0:

            message("JOIN1")
            gtf0 = gtf.add_attr_from_dict(feat="gene",
                                          key=identifier,
                                          a_dict=gene_closest,
                                          new_key="closest_gn"
                                          )
            gtf1 = gtf0.add_attr_from_dict(feat="gene",
                                           key=identifier,
                                           a_dict=gene_closest_dist,
                                           new_key="closest_dist")

            if add_strands:
                message("JOIN3")
                gtf2 = gtf1.add_attr_from_dict(feat="gene",
                                               key=identifier,
                                               a_dict=gene_closest_strand,
                                               new_key="closest_strand")

        gtf2.write(outputfile)


Then everything is ok... But this is clearly not efficient from a memory point of view when working with large datasets (and also not reasonable for a developper using the API...).


    $ gtftk get_example |  bedtools sort | gtftk closest_genes -n 2  -t gene -r gene -a -K /tmp/toto -V 2 2>&1 | perl -ne 'print if(/(closest_gn)|(created)|(Freing)/)'
        |--- 11:29-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7f8234bb92a0, id=4534455184, nb=1).
        |--- 11:29-DEBUG-closest_genes : GTF created (nb_lines=10, file_name=-, ptr_addr=0x7f8234c22480, id=4534203280, nb=2).
        |--- 11:29-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7f823727aec0, id=4533888400, nb=3).
        |--- 11:29-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7f8234e45ea0, id=4533887440, nb=4).
        |--- 11:29-DEBUG-closest_genes : GTF created (nb_lines=70, file_name=-, ptr_addr=0x7f8234e4bfd0, id=4533887824, nb=5).
        |--- 11:29-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7f8234bb92a0, id=4534455184, nb=1).
        |--- 11:29-DEBUG-closest_genes : Freing (nb_lines=10, file_name=-, ptr_addr=0x7f8234c22480, id=4534203280, nb=2).
        |--- 11:29-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7f823727aec0, id=4533888400, nb=3).
        |--- 11:29-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7f8234e45ea0, id=4533887440, nb=4).
        |--- 11:29-DEBUG-closest_genes : Freing (nb_lines=70, file_name=-, ptr_addr=0x7f8234e4bfd0, id=4533887824, nb=5).
    ['gene_id', 'closest_gn', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'transcript_id', 'ccds_id', 'exon_id']
    ['gene_id', 'closest_gn', 'closest_dist', 'closest_strand', 'transcript_id', 'ccds_id', 'exon_id']
    chr1    gtftk   gene    3   14  .   -   .   gene_id "G0009"; closest_gn "G0006,G0005"; closest_dist "8,19"; closest_strand "-,-";
    chr1    gtftk   gene    22  35  .   -   .   gene_id "G0006"; closest_gn "G0005,G0009"; closest_dist "0,8"; closest_strand "-,-";
    chr1    gtftk   gene    33  47  .   -   .   gene_id "G0005"; closest_gn "G0006,G0003"; closest_dist "0,3"; closest_strand "-,-";
    chr1    gtftk   gene    50  61  .   -   .   gene_id "G0003"; closest_gn "G0005,G0004"; closest_dist "3,4"; closest_strand "-,+";
    chr1    gtftk   gene    65  76  .   +   .   gene_id "G0004"; closest_gn "G0003,G0005"; closest_dist "4,18"; closest_strand "-,-";
    chr1    gtftk   gene    107 116 .   +   .   gene_id "G0007"; closest_gn "G0001,G0004"; closest_dist "9,31"; closest_strand "+,+";
    chr1    gtftk   gene    125 138 .   +   .   gene_id "G0001"; closest_gn "G0007,G0010"; closest_dist "9,38"; closest_strand "+,+";
    chr1    gtftk   gene    176 186 .   +   .   gene_id "G0010"; closest_gn "G0002,G0008"; closest_dist "0,24"; closest_strand "+,-";
    chr1    gtftk   gene    180 189 .   +   .   gene_id "G0002"; closest_gn "G0010,G0008"; closest_dist "0,21"; closest_strand "+,-";
    chr1    gtftk   gene    210 222 .   -   .   gene_id "G0008"; closest_gn "G0002,G0010"; closest_dist "21,24"; closest_strand "+,+";

**Comment by dputhier** [comment]
This one should be fixed in 3842712477a147f8d2c079f625148cc90c719ac5.

**Comment by dputhier** [comment]
Re-opening this issue. In the last devel version of libgtftk we have and issue when joining/adding iteratively 3 keys to a GTF object. With problems on free_gtf_data, this is the only bug I encounter when testing all commands.

        if not text_format:

            if len(gene_closest) > 0:

                message("JOIN1")
                gtf = gtf.add_attr_from_dict(feat="gene",
                                             key=identifier,
                                             a_dict=gene_closest,
                                             new_key="closest_gn"
                                             )
                gtf = gtf.add_attr_from_dict(feat="gene",
                                             key=identifier,
                                             a_dict=gene_closest_dist,
                                             new_key="closest_dist")

                if add_strands:
                    message("JOIN3")
                    gtf = gtf.add_attr_from_dict(feat="gene",
                                                 key=identifier,
                                                 a_dict=gene_closest_strand,
                                                 new_key="closest_strand")

**Comment by dputhier** [comment]
Re-opening this issue. In the last devel version of libgtftk we have and issue when joining/adding iteratively 3 keys to a GTF object. With problems on free_gtf_data, this is the only bug I encounter when testing all commands.

        if not text_format:

            if len(gene_closest) > 0:

                message("JOIN1")
                gtf = gtf.add_attr_from_dict(feat="gene",
                                             key=identifier,
                                             a_dict=gene_closest,
                                             new_key="closest_gn"
                                             )
                gtf = gtf.add_attr_from_dict(feat="gene",
                                             key=identifier,
                                             a_dict=gene_closest_dist,
                                             new_key="closest_dist")

                if add_strands:
                    message("JOIN3")
                    gtf = gtf.add_attr_from_dict(feat="gene",
                                                 key=identifier,
                                                 a_dict=gene_closest_strand,
                                                 new_key="closest_strand")

**Comment by dputhier** [comment]
Seems to be OK now in f52ee3078a34aa5b3417fb82161ffb26e4fd3261
