### ISSUE TITLE
convert_to_ensembl

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#37]
Salut Fafa,
J'ai une segfault avec le fichier suivant quand j'utilise convert_to_ensembl. Pourrais tu regarder ?
Merci

       /gpfs/tagc/home/puthier/005_LAN_RNA-SEQ_ILLUMINA_NEW/ANNOTATIONS/GTF/gencode.vM1.annotation.gtf

**Comment by dputhier** [comment]
Note que dans ce fichier certaines clef/valeurs sont sous la forme:

clef valeur; 

au lieu de :

clef "valeur"

Cependant, je ne sais pas si ça provient de là.
A+

**Comment by fafa13** [comment]
En fait, dans les lignes "gene", il y a un attribut transcript_id avec pour valeur le gene_id, ce qui n'est pas très logique. Cela dit, la librairie ne devrait pas planter pour ça, je vais corriger asap.

**Comment by dputhier** [comment]
on pourrait même dire illogique... Travail de débutant...
Ciao

**Comment by fafa13** [comment]
Ca marche maintenant, mais le fichioer initial est déjà au format Ensembl, ce qui fait que convert_to_ensembl donne le même fichier en sortie, avec tous les attributs sous la forme 
`clef "valeur"`
Et sans les commentaires. A ce propos, doit-on conserver les commentaires ou peut-on les supprimer joyeusement ?

**Comment by dputhier** [comment]
Ca marche mais je me demande si tu as soumis (?). Tu devrais, quand tu soumet, ajouter le sha courant dans un message de fermeture et cloturer le thread.
Ciao
