### ISSUE TITLE
segfault convert_ensembl

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#38]
I have a problem converting a file in ensembl format. I have extracted the first 1000 lines so that you can check on your side. I guess the problem is related to some file format issue. The gtf was obtained from UCSC (hg38 genome, table old_ucsc_genes>KnownGeneOld9).

    gtftk convert_ensembl  -V 2 -i old_ucsc_genes_hg38_1k.gtf
        |--- 13:07-DEBUG : Creating a GTF instance
        |--- 13:07-DEBUG : GTF created  : #lines=1000 ;  File con=old_ucsc_genes_hg38_1k.gtf ; address=0x7fa248091840
        |--- 13:07-INFO : Calling convert_to_ensembl
     Segmentation fault: [11]([url](url))

[old_ucsc_genes_hg38_1k.gtf.zip](https://github.com/dputhier/libgtftk/files/1119289/old_ucsc_genes_hg38_1k.gtf.zip)

**Comment by fafa13** [comment]
Hello I'm back on gtftk !
The GTF file you use is not valid. There is a space character at the end of each line that should not be here !!!
OK, removing those spaces is required but not enough to solve the problem. So, first remove the spaces and then, get the last push of the library (branch 3_2). I fixed some nasty bugs in convert_to ensembl function ... and I also commented out a part of **select_by_positions** function you added because it doesn't compile anymore because of the changes I did in GTF_ROW structure. Sorry ...

**Comment by dputhier** [comment]
Hi Fafa,
Aie... Bien vu... Just keep in mind that  **select_by_positions** is required now for several commands... Do you plan to resurect it ??
Ciao

**Comment by fafa13** [comment]
Oh, I hoped you did it by yourself ...
Well, it's done. Try it to check if it works like before.

**Comment by dputhier** [comment]
Now I get the following error:

    $ gtftk convert_ensembl -i ~/Downloads/old_ucsc_genes_hg38_1k.gtf
    python(75977,0x7fff7c073000) malloc: *** error for object 0x7ffbbc843348: incorrect checksum for freed object - object was probably modified after being freed.
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

Or sometimes this error:

    $ gtftk convert_ensembl -i ~/Downloads/old_ucsc_genes_hg38_1k.gtf
    Segmentation fault: 11

Or sometimes it works.

Or sometimes the segfault happen at the end of the processing.

**Comment by dputhier** [comment]
J'ajoute les les clefs/valeurs contiennent parfois des trucs bizarre:

"+-------------------+---------------+";
"the";
"public";
...

Quand ça marche, ces clefs n'apparaissent pas. Il y a sans doute une petite fuite mémoire dans le coin.

A+

**Comment by dputhier** [comment]
For information, this one is specific of OSX for the segfault that happens after job has been complete. Note the strange key/values ( "?E"; "P?M";...) is observed on both UNIX and OSX.

    gtftk convert_ensembl  -V 2 -i ~/Downloads/old_ucsc_genes_hg38_1k.gtf
        |--- 8:41-DEBUG-convert_ensembl : Creating a GTF instance.
        |--- 8:41-DEBUG_MEM-convert_ensembl : GTF created (nb_lines=1000, file_name=/Users/puthier/Downloads/old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fdb5629bb50, id=4434738064, nb=1).
        |--- 8:41-INFO-convert_ensembl : Calling convert_to_ensembl
        |--- 8:41-INFO-convert_ensembl : Checking gene to chromosome mapping
        |--- 8:41-DEBUG-convert_ensembl : Creating a GTF instance.
        |--- 8:41-DEBUG_MEM-convert_ensembl : GTF created (nb_lines=1316, file_name=/Users/puthier/Downloads/old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fdb53524860, id=4434432848, nb=2).
        |--- 8:41-DEBUG_MEM-convert_ensembl : GTF deleted (nb_lines=1000, file_name=/Users/puthier/Downloads/old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fdb5629bb50, id=4434738064, nb=1).
        |--- 8:41-DEBUG-convert_ensembl : Writing a GTF (nb_lines=1316, file_name=/Users/puthier/Downloads/old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fdb53524860, id=4434432848, nb=2).
    chr1  hg38_knownGeneOld9  gene  17369 17436 0.000000  - . gene_id "uc031tla.1";
    chr1  hg38_knownGeneOld9  transcript  17369 17436 0.000000  - . gene_id "uc031tla.1"; transcript_id "uc031tla.1";  "?E";


    ....
    ....
    ....
    chr1  hg38_knownGeneOld9  start_codon 999971  999973  0.000000  - . gene_id "uc001aci.3"; transcript_id "uc001aci.3";  "P?M";
    chr1  hg38_knownGeneOld9  exon  999866  1000111 0.000000  - . gene_id "uc001aci.3"; transcript_id "uc001aci.3";
        |--- 8:41-INFO-convert_ensembl : GTF written.
        |--- 8:41-DEBUG_MEM-convert_ensembl : GTF deleted (nb_lines=1316, file_name=/Users/puthier/Downloads/old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fdb53524860, id=4434432848, nb=2).
    Segmentation fault: 11

**Comment by fafa13** [comment]
I don't have those strange key/values with UNIX. But I have only 1000 lines in the GTF file, not 1316 like in your example.

**Comment by fafa13** [comment]
Oh I understand, 1316 is the number of lines in the converted file ...

**Comment by fafa13** [comment]
Works well on sacapus too.

**Comment by dputhier** [comment]
Almost good but it ends up with a segfault:

        $ gtftk convert_ensembl  -V 2 -i old_ucsc_genes_hg38_1k.gtf -o toto
            |--- 22:55-DEBUG-convert_ensembl : Creating a GTF instance.
        python(92690,0x7fff71415000) malloc: *** error for object 0x7ffacf823c68: incorrect checksum for freed object - object was probably modified after being freed.
        *** set a breakpoint in malloc_error_break to debug
        Abort trap: 6

**Comment by dputhier** [comment]
And sometimes I get another msg:

        $ gtftk convert_ensembl  -V 2 -i old_ucsc_genes_hg38_1k.gtf -o toto
            |--- 22:56-DEBUG-convert_ensembl : Creating a GTF instance.
            |--- 22:56-DEBUG_MEM-convert_ensembl : GTF created (#lines=1000, file=old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fa25835ed30, id=4378561552, nb=1).
            |--- 22:56-INFO-convert_ensembl : Calling convert_to_ensembl
            |--- 22:56-INFO-convert_ensembl : Checking gene to chromosome mapping
            |--- 22:56-DEBUG-convert_ensembl : Creating a GTF instance.
            |--- 22:56-DEBUG_MEM-convert_ensembl : GTF created (#lines=1316, file=old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fa258105ff0, id=4378289936, nb=2).
            |--- 22:56-DEBUG_MEM-convert_ensembl : GTF deleted (#lines=1000, file=old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fa25835ed30, id=4378561552, nb=1).
            |--- 22:56-DEBUG-convert_ensembl : Writing a GTF (#lines=1316, file=old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fa258105ff0, id=4378289936, nb=2).
            |--- 22:56-INFO-convert_ensembl : GTF written.
            |--- 22:56-DEBUG_MEM-convert_ensembl : GTF deleted (#lines=1316, file=old_ucsc_genes_hg38_1k.gtf, ptr_addr=0x7fa258105ff0, id=4378289936, nb=2).
        Segmentation fault: 11

**Comment by dputhier** [comment]
I'm adding some information related to this bug. The bug appears to be very rare (although it is encountered 1 time out of 10) when the stdin is used:

cat old_ucsc_genes_hg38_1k.gtf |  gtftk convert_ensembl | md5sum-lite
fb833a9d4116925678610e2da5007d23
cat old_ucsc_genes_hg38_1k.gtf |  gtftk convert_ensembl | md5sum-lite
fb833a9d4116925678610e2da5007d23

When -i is used it is clearly worth and irremediably ends up with a segfault. Strange.

**Comment by fafa13** [comment]
I made a push for this bug. Could you test it from python ?

**Comment by dputhier** [comment]
Upgraded to the last version. Still getting some segfault. Memory seems to go beyond what it should as some value for keys are "C:\Users\<username>\AppData\Roaming\<AppAuthor>\<AppName>".... (but I'm not working under windows :).

**Comment by fafa13** [comment]
This one works now !

**Comment by dputhier** [comment]
Too nice !
Closing
