### ISSUE TITLE
Exon numbering

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#39]
Ce serait intéressant d'avoir une méthode qui permet d'annoter les exons en indiquant leur position dans le transcrit. Je l'ai fait sous la forme d'une commande. Maintenant j'aimerais le faire sous la forme d'une méthode pour l'objet GTF. Ca reste un peu lent en Python et je me rends compte qu'on peut fréquemment en avoir besoin.
Ciao

**Comment by fafa13** [comment]
La fonction est faite. Elle est toute simple, voilà son prototype:

`GTF_DATA *add_exon_number(GTF_DATA *)
`

Elle ajoute le numéro de l'exon sur chaque ligne "exon". A noter qu'elle ne modifie pas les autres lignes (UTRs, stop et start codon, CDS) alors que le numéro de l'exon est présent dans ces lignes dans les fichiers Ensembl. Donc, la question est : est-ce que cette fonction doit ajouter le numéro de l'exon dans toutes les lignes ou bien seulement dans les lignes "exon" ?

**Comment by dputhier** [comment]
Salut fafa,
Je n'avais pas réalisé que cette info était proposée par ensembl pour les élements autres que les exons. Là, c'est à toi de nous dire. La fonction que tu a codée convient au besoin qui sont les miens dans l'immédiat. Cependant, je suis certain que ce que tu proposes pourrait élargir l'ensemble des possibles.

**Comment by dputhier** [comment]
Par contre ce serait bien de pouvoir choisir le nom du champ (genre exon_number par défaut).

**Comment by dputhier** [comment]
En plus de pouvoir choisir le nom du champ ce serait bien que la fonction soit dispo. Il me semble que tu n'as pas soumis :)?

**Comment by dputhier** [comment]
Implemented in f52ee3078a34aa5b3417fb82161ffb26e4fd3261
