### ISSUE TITLE
Strange behaviour of get_sequence

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#43]
Trying to fixe some minor issue I ended up with a very particular problem with get_sequence.

In one one file I have a chromosome which is unknown and wont appear in the GTF:

	$ cat /tmp/simple.fa 
	>CACA
	ttcaatgaggattgccg...

In one other file I have the right chromosome:

	$ cat gtftk/data/simple/simple.fa
	>chr1
	ttcaatgaggattgccg...

But when I call gtftk with one or the other file, I get the same result...

    $ gtftk get_tx_seq -V 2  -i gtftk/data/simple/simple.gtf -g gtftk/data/simple/simple.fa 
        |--- 10:18-INFO-get_tx_seq : 1 fasta files found.
        |--- 10:18-INFO-get_tx_seq : Checking fasta file chromosome list
        |--- 10:18-DEBUG-get_tx_seq : Creating a GTF instance.
        |--- 10:18-DEBUG-get_tx_seq : Calling extract_data_iter.
        |--- 10:18-DEBUG-get_tx_seq : Ensembl format detected.
        |--- 10:18-DEBUG_MEM-get_tx_seq : GTF created (nb_lines=70, file_name=gtftk/data/simple/simple.gtf, ptr_addr=0x7fe4551ecc90, id=4430370768, nb=1).
        |--- 10:18-DEBUG-get_tx_seq : Calling 'get_chroms'.
        |--- 10:18-INFO-get_tx_seq : Using genome file:gtftk/data/simple/simple.fa
        |--- 10:18-INFO-get_tx_seq : Retrieving fasta sequences from gtftk/data/simple/simple.fa
        |--- 10:18-DEBUG-get_tx_seq : Calling 'get_sequences' method.
        |--- 10:18-DEBUG-get_tx_seq : Calling select_by_key (key=feature, value=transcript)
        |--- 10:18-DEBUG-get_tx_seq : Creating a GTF instance.
        |--- 10:18-DEBUG_MEM-get_tx_seq : GTF created (nb_lines=15, file_name=gtftk/data/simple/simple.gtf, ptr_addr=0x7fe457b85000, id=4430239312, nb=2).
        |--- 10:18-DEBUG-get_tx_seq : Calling extract_data.
    >transcript|G0001T002|G0001|chr1|125|138
    cccccgttacgtag
    >transcript|G0001T001|G0001|chr1|125|138
    cccccgttacgtag
    ...

    $ gtftk get_tx_seq -V 2  -i gtftk/data/simple/simple.gtf -g /tmp/simple.fa              
        |--- 10:19-INFO-get_tx_seq : 1 fasta files found.
        |--- 10:19-INFO-get_tx_seq : Checking fasta file chromosome list
        |--- 10:19-DEBUG-get_tx_seq : Creating a GTF instance.
        |--- 10:19-DEBUG-get_tx_seq : Calling extract_data_iter.
        |--- 10:19-DEBUG-get_tx_seq : Ensembl format detected.
        |--- 10:19-DEBUG_MEM-get_tx_seq : GTF created (nb_lines=70, file_name=gtftk/data/simple/simple.gtf, ptr_addr=0x7feca51eeef0, id=4605717200, nb=1).
        |--- 10:19-DEBUG-get_tx_seq : Calling 'get_chroms'.
        |--- 10:19-INFO-get_tx_seq : Using genome file:/tmp/simple.fa

        |--- 10:19-INFO-get_tx_seq : Retrieving fasta sequences from /tmp/simple.fa
        |--- 10:19-DEBUG-get_tx_seq : Calling 'get_sequences' method.
        |--- 10:19-DEBUG-get_tx_seq : Calling select_by_key (key=feature, value=transcript)
        |--- 10:19-DEBUG-get_tx_seq : Creating a GTF instance.
        |--- 10:19-DEBUG_MEM-get_tx_seq : GTF created (nb_lines=15, file_name=gtftk/data/simple/simple.gtf, ptr_addr=0x7feca51d9890, id=4605412176, nb=2).
        |--- 10:19-DEBUG-get_tx_seq : Calling extract_data.
    >transcript|G0001T002|G0001|chr1|125|138
    cccccgttacgtag
    >transcript|G0001T001|
    ...

Totally weird. I can' get it... Are you using any cache or index ?

**Comment by fafa13** [comment]
I understand what happens. When you use the first fasta file (with chr1), the library creates an index in ~/.gtftk called simple.fa.gtftk. As the second fasta file (with CACA) has the same name (simple.fa), the index is not recreated and so, the names of the chromosomes are those of the first fasta file. If you modify the GTF file by replacing "chr1" by "CACA", you won't get any results because in the index file, there is no CACA chromosome, even if there is one in the fasta file.

**Comment by dputhier** [comment]
Maybe the program should store a MD5 Checksum to check whether or not this is the same file.

**Comment by fafa13** [comment]
Yes, or the CRC of the fasta file. There is a crc() function in C in linux. I hope it exists also in Mac OS ...

**Comment by fafa13** [comment]
It should be fixed now. The CRC32 is added at the end of the genome indexes files in .gtftk directory. That means that each time you use a fasta genome file, you recompute the CRC32 to check if it is the same value as the one in the index file. We lose a few seconds again ...

**Comment by dputhier** [comment]
Seems to be fixed.
