### ISSUE TITLE
Error upon exit of convert_ensembl

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#48]
I get a "pointer being freed was not allocated" when exiting convert_ensembl.
A+

The bug is  not observed using the mini_real dataset but can be observed using a full/large gtf:

	# everything is fine with the mini_real dataset
	gtftk get_example -d mini_real |  gtftk select_by_key -V 2 -C -k feature -v exon  | gtftk convert_ensembl -V 2 -o bla

Here with ensembl Hs (release 90)

	# Problem when working with the full ensembl dataset (release 90 here)
	$ gtftk retrieve -c -s homo_sapiens | gtftk select_by_key -V 2 -C -k feature -v exon  | gtftk convert_ensembl -V 2 -o bla
    |--- 15:48-DEBUG-select_by_key : Creating a GTF instance.
    |--- 15:48-DEBUG-convert_ensembl : Creating a GTF instance.
    |--- 15:48-DEBUG_MEM-select_by_key : GTF created (nb_lines=2612129, file_name=-, ptr_addr=0x7fb7f6c9e1b0, id=4442712656, nb=1).
    |--- 15:48-DEBUG-select_by_key : Calling select_by_key (key=feature, value=exon)
    |--- 15:48-DEBUG-select_by_key : Creating a GTF instance.
    |--- 15:48-DEBUG_MEM-select_by_key : GTF created (nb_lines=1199596, file_name=-, ptr_addr=0x7fb731c3efc0, id=4442405328, nb=2).
    |--- 15:48-DEBUG_MEM-select_by_key : GTF deleted (nb_lines=2612129, file_name=-, ptr_addr=0x7fb7f6c9e1b0, id=4442712656, nb=1).
    |--- 15:48-DEBUG-select_by_key : Writing a GTF (nb_lines=1199596, file_name=-, ptr_addr=0x7fb731c3efc0, id=4442405328, nb=2).
    |--- 15:49-INFO-select_by_key : GTF written.
    |--- 15:49-DEBUG_MEM-select_by_key : GTF deleted (nb_lines=1199596, file_name=-, ptr_addr=0x7fb731c3efc0, id=4442405328, nb=2).
    |--- 15:49-DEBUG_MEM-convert_ensembl : GTF created (nb_lines=1199596, file_name=-, ptr_addr=0x7ff8c0371e90, id=4544551376, nb=1).
    |--- 15:49-INFO-convert_ensembl : Calling convert_to_ensembl
    |--- 15:49-INFO-convert_ensembl : Checking gene to chromosome mapping
    |--- 15:49-DEBUG-convert_ensembl : Creating a GTF instance.
    |--- 15:49-DEBUG_MEM-convert_ensembl : GTF created (nb_lines=1458082, file_name=-, ptr_addr=0x7ff868763680, id=4544242448, nb=2).
    |--- 15:49-DEBUG_MEM-convert_ensembl : GTF deleted (nb_lines=1199596, file_name=-, ptr_addr=0x7ff8c0371e90, id=4544551376, nb=1).
    |--- 15:49-DEBUG-convert_ensembl : Writing a GTF (nb_lines=1458082, file_name=-, ptr_addr=0x7ff868763680, id=4544242448, nb=2).
    |--- 15:49-INFO-convert_ensembl : GTF written.
    |--- 15:49-DEBUG_MEM-convert_ensembl : GTF deleted (nb_lines=1458082, file_name=-, ptr_addr=0x7ff868763680, id=4544242448, nb=2).
	python(37077,0x7fff7a7af000) malloc: *** error for object 0x7ff7f7ea7f20: pointer being freed was not allocated
	*** set a breakpoint in malloc_error_break to debug
	Abort trap: 6

**Comment by dputhier** [comment]
Things are going really better here but we still have a slight problem with freeing at the end of this call in f52ee3078a34aa5b3417fb82161ffb26e4fd3261.

        $ gtftk retrieve -c -s homo_sapiens | gtftk select_by_key -V 2 -C -k feature -v exon  | gtftk convert_ensembl -V 2 -o bla
            |--- 22:45-DEBUG-select_by_key : Creating a GTF instance.
            |--- 22:45-DEBUG-convert_ensembl : Creating a GTF instance.
            |--- 22:45-DEBUG_MEM-select_by_key : GTF created (#lines=2612129, file=-, ptr_addr=0x7ffca82437f0, id=4510039120, nb=1).
            |--- 22:45-DEBUG-select_by_key : Calling select_by_key (key=feature, value=exon)
            |--- 22:45-DEBUG-select_by_key : Creating a GTF instance.
            |--- 22:45-DEBUG_MEM-select_by_key : GTF created (#lines=1199596, file=-, ptr_addr=0x7ffbe3015e30, id=4509761744, nb=2).
            |--- 22:45-DEBUG_MEM-select_by_key : GTF deleted (#lines=2612129, file=-, ptr_addr=0x7ffca82437f0, id=4510039120, nb=1).
            |--- 22:46-DEBUG-select_by_key : Writing a GTF (#lines=1199596, file=-, ptr_addr=0x7ffbe3015e30, id=4509761744, nb=2).
            |--- 22:46-INFO-select_by_key : GTF written.
            |--- 22:46-DEBUG_MEM-select_by_key : GTF deleted (#lines=1199596, file=-, ptr_addr=0x7ffbe3015e30, id=4509761744, nb=2).
            |--- 22:46-DEBUG_MEM-convert_ensembl : GTF created (#lines=1199596, file=-, ptr_addr=0x7fd0a50c9a80, id=4521421776, nb=1).
            |--- 22:46-INFO-convert_ensembl : Calling convert_to_ensembl
            |--- 22:46-INFO-convert_ensembl : Checking gene to chromosome mapping
            |--- 22:46-DEBUG-convert_ensembl : Creating a GTF instance.
            |--- 22:46-DEBUG_MEM-convert_ensembl : GTF created (#lines=1458082, file=-, ptr_addr=0x7fd04c6f8340, id=4521111504, nb=2).
            |--- 22:46-DEBUG_MEM-convert_ensembl : GTF deleted (#lines=1199596, file=-, ptr_addr=0x7fd0a50c9a80, id=4521421776, nb=1).
            |--- 22:46-DEBUG-convert_ensembl : Writing a GTF (#lines=1458082, file=-, ptr_addr=0x7fd04c6f8340, id=4521111504, nb=2).
            |--- 22:46-INFO-convert_ensembl : GTF written.
            |--- 22:46-DEBUG_MEM-convert_ensembl : GTF deleted (#lines=1458082, file=-, ptr_addr=0x7fd04c6f8340, id=4521111504, nb=2).
        python(91530,0x7fff71415000) malloc: *** error for object 0x7fcfdcf28b30: pointer being freed was not allocated
        *** set a breakpoint in malloc_error_break to debug
        Abort trap: 6

**Comment by fafa13** [comment]
Good news : this bug is not python specific. The C client give the same 
results. Should be not so hard to fix ...

**Comment by dputhier** [comment]
And then it will tend toward perfection...
