### ISSUE TITLE
extract_data

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#5]
@fafa13 , 
Do you plan to resurect the extract_data function ? Numerous commands on the python side depend on this function.

**Comment by fafa13** [comment]
This is the next one in the list.

I have just pushed a version with "select_by_genomic_location" and 
"select_by_number_of_exon".

**Comment by dputhier** [comment]
Cool. I will have a look.

**Comment by dputhier** [comment]
select_by_number_of_exon : Implemented and tested.

**Comment by dputhier** [comment]
Je viens d'interfacer select_by_genomic_location. Intéressant, la manière avec laquelle on peut convertir des listes en pointeurs : 

      *select_by_genomic_location(GTF_DATA *gtf_data, int nb_loc, char **chr, int *begin_gl, int *end_gl);

Voilà comment on convertit une liste en un  char **chr:

     chr_list = ["AAA", "BBB", "CCC"]
     chr_ptr = (ctypes.c_char_p * len(chr_list))(*chr_list)

Et comment on convertit une liste d'int en un int *begin_gl:

     start_ptr = [1,2, 5]
     start_ptr = (ctypes.c_int * len(start_list))(*start_list)
