### ISSUE TITLE
extract_data uniq argument

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#52]
I had issues with tests related to extract_data in tabulate. I had a look at the uniq argument. It seems it does not do exactly what it should. On the simple_01 dataset that contains 70 lines the uniq argument returns 2 lines...

        In [12]: TAB("ds", gtf._dll.extract_data(gtf._data, "gene_id,transcript_id", 0, 0))
        Out[12]: 

        - A TAB object containing 70 lines:
        - File connection: ds
        G0001   .
        G0001   G0001T002
        G0001   G0001T002
        G0001   G0001T002
        G0001   G0001T001
        G0001   G0001T001

        In [13]: TAB("ds", gtf._dll.extract_data(gtf._data, "gene_id,transcript_id", 0, 1))
        Out[13]: 

        - A TAB object containing 2 lines:
        - File connection: ds
        G0001   .
        G0001   G0001T002

**Comment by fafa13** [comment]
Fixed !

**Comment by dputhier** [comment]
Looks good. Closed
