### ISSUE TITLE
get_feature_list

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#53]
I'm getting problem when using get_feature_list. It should return a 2 column matrix as a TTEXT structure. The problem is that I'm unable to get the column containing the counts. The second columns contains a cdata 'char *' NULL.

        ptr=gtf._dll.get_attribute_list(gtf._data)
        ffi.string(ptr.data[1][0]) # 'transcript_id'
        In [35]: ptr.data[1][1]
        Out[35]: <cdata 'char *' NULL>

**Comment by dputhier** [comment]
This one is not fixed in f52ee3078a34aa5b3417fb82161ffb26e4fd3261. Should be checked.

**Comment by fafa13** [comment]
Sorry for this one but it is not really a bug, just a dirty usage of the TTEXT structure. Normally, the TTEXT structure is made for storing a matrix. But get_attribute_list returns a list. So :
- the first dimension of ptr.data is the rank of the attribute in the list (0, 1, 2, .... ,N - 1 if N is the number of attributes in the list)
- the second dimension is always (and only) 0 and points to the string (the attribute)
- the third dimension doesn't exist ...

I did that to avoid creating a new data structure to store a list. If you prefer to have a special data structure for lists, I can do it.

**Comment by dputhier** [comment]
OK. Thx fafa. I will close this one.
