### ISSUE TITLE
extract_data

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#6]
I have pushed the **extract_data** function.
Here is the definition of this function :

`RAW_DATA *extract_data(GTF_DATA *gtf_data, char *key)`

key contains a list of columns or attributes to be extracted, separated by "," character.
Ex : extract_data(gtf_data, "seqid,feature,start,end,gene_name")

The return value is a pointer on a RAW_DATA structure, used to store a matrix of strings.
This structure is defined as:

```
typedef struct RAW_DATA {
	int nb_rows, nb_columns;
	char **column_name;
	char ***data;
} RAW_DATA;

```
**nb_rows** and **nb_columns** define the size of the matrix
**column_name** is a table of strings containing the names of the columns (the words in the key parameter of extract_data function)
**data** is the matrix of strings (data[x][y] is the string in the row x in the column y)

There is also a function called 
`
print_raw_data(RAW_DATA *raw_data, char delim)
`
to print a RAW_DATA in standard output, with the given single character delimiter

**Comment by dputhier** [comment]
I have interfaced the function without any problem. However, I'm unable to retrieve the column names. I tried with various solutions. Here is the current python implementation:


     class _RAW_DATA(Structure):
         """A structure containing rows of a tabulated GTF file."""
         _fields_ = [("nb_rows", c_int),
                     ("nb_columns", c_int),
                     ("column_name", POINTER(c_char_p)),
                     ("data", POINTER(POINTER(c_char_p)))]
