### ISSUE TITLE
select_transcript(self._data, 1) has became erratic since last push

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#66]
It seems that select_transcript has became erratic since the last push. Problems are also encountered with select_transcript(self._data, 3).

    $ gtftk short_long -i gtftk/data/simple_03/simple_short_long.gtf  -g | wc -l
          53
    $ gtftk short_long -i gtftk/data/simple_03/simple_short_long.gtf  -g | wc -l
          51

**Comment by fafa13** [comment]
This is not really a bug. In fact, 2 transcripts have the same length. So gtftk returns one of them but not always the same. I cannot change this for it is due to the index handling by the C library. The question is : what to do when several transcripts have the same length ?

**Comment by dputhier** [comment]
Aie. Sorry for this one. Maybe we should take the first encountered transcript or select one of them randomly but exposing an argument to set the seed of the random number generator. Maybe the first solution would be the simplest. But it may be complicated by the fact that you are dealing with an index. By the way, I guess ot would be better to have a reproducible output.

**Comment by dputhier** [comment]
fixed in 2714b90bfb90a15c74c6bf0012b4097e0ac99582
