### ISSUE TITLE
Convert_ensembl

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#67]
Coming back with convert_ensembl :).

		gtftk short_long -C -l -V 2 -i Homo_sapiens.GRCh38.91.chr.gtf.gz | gtftk convert_ensembl -V 2
		|--- 10:58-DEBUG_MEM-convert_ensembl : GTF deleted (#lines=641667, file=-, ptr_addr=0x7fbeb2db8830, id=4427222224, nb=2).
		python(49366,0x7fff77bed000) malloc: *** error for object 0x7fbeb2db9be0: pointer being freed was not allocated
		*** set a breakpoint in malloc_error_break to debug
		Abort trap: 6

**Comment by fafa13** [comment]
The last push seems to fix this one too ... to be confirmed !
Well, the conversion to ensembl works but there is still a malloc error at the end.

**Comment by dputhier** [comment]
Yes, convertion works but ends up with a segfault when deleting GTF from memory.

**Comment by fafa13** [comment]
Can you try now ?

**Comment by dputhier** [comment]
Whaou :). I guess this one is fixed now !
