### ISSUE TITLE
merge_attr

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#72]
Strange behaviour of merge_attr that leads to segfault in command line. Have a look at the merged keys. Available in last version ("e15b8c7865e57d1e504430cd92daffe4d2454cd6") of pygtftk.

		from gtftk.utils import get_example_file
		from gtftk.utils import get_example_file
		a_file = get_example_file("simple", "gtf")[0]
		a_gtf = GTF(a_file)
		a_gtf.merge_attr(feat="*", keys="transcript_id,gene_id", new_key="bla_key", sep="|")

		chr1	gtftk	gene	125	138	.	+	.	gene_id "G0001"; bla_key ".|..|G0001";
		chr1	gtftk	transcript	125	138	.	+	.	gene_id "G0001"; transcript_id "G0001T002"; bla_key "G0001T002|.G0001T002|G0001";
		chr1	gtftk	exon	125	138	.	+	.	gene_id "G0001"; transcript_id "G0001T002"; exon_id "G0001T002E001"; bla_key "G0001T002|.G0001T002|G0001";
		chr1	gtftk	CDS	125	130	.	+	.	gene_id "G0001"; transcript_id "G0001T002"; ccds_id "CDS_G0001T002"; bla_key "G0001T002|.G0001T002|G0001";
		chr1	gtftk	transcript	125	138	.	+	.	gene_id "G0001"; transcript_id "G0001T001"; bla_key "G0001T001|.G0001T001|G0001";
		chr1	gtftk	exon	125	138	.	+	.	gene_id "G0001"; transcript_id "G0001T001"; exon_id "G0001T001E001"; bla_key "G0001T001|.G0001T001|G0001";

**Comment by dputhier** [comment]
Note that the only code related to this is a call to libgtftk::merge_attr

**Comment by fafa13** [comment]
I have pushed a fix for this bug.  Try again and let me know ...

**Comment by dputhier** [comment]
OK. The tests are ok now. Closing
