### ISSUE TITLE
Issue with libgtftk.get_sequences (this one looks simple)

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#74]
I have noticed that the first call to libgtftk.get_sequences leads to always to a NULL string, indicating that the sequence is not available in the SEQFRAG pointer. In my tests, after a fresh install (with an existing ~/.gtftk directory) the index is not available and will be produced during the first call.
If I call the function another time, the index is now available and it will work like a charm for years. I guess that there is something that is related to index access at first call to get_sequences. The file is maybe locked ?

**Comment by fafa13** [comment]
I just pushed a fix for this bug.
