### ISSUE TITLE
Some issues encountered using a docker env

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#83]
pygtftk/src/libgtftk/command/get_sequences.c:78:4: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
		    fgets(ret + N - reste_row, toget + 1, fasta_file);
		    ^

		pygtftk/src/libgtftk/command/convert_to_ensembl.c:190:5: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
		     asprintf(&(g_row->field[3]), "%d", start);
		     ^
		pygtftk/src/libgtftk/command/convert_to_ensembl.c:191:5: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
		     asprintf(&(g_row->field[4]), "%d", end);
		     ^
		pygtftk/src/libgtftk/command/convert_to_ensembl.c: In function 'action_transcript':
		pygtftk/src/libgtftk/command/convert_to_ensembl.c:98:5: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
		     asprintf(&(tr_row->field[3]), "%d", start);
		     ^
		pygtftk/src/libgtftk/command/convert_to_ensembl.c:99:5: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
		     asprintf(&(tr_row->field[4]), "%d", end);
		     ^

**Comment by fafa13** [comment]
The workaround to avoid those warnings is to add the `-Wno-unused-result` parameter when compiling the library.

**Comment by fafa13** [comment]
I pushed fixes that should remove these warnings.

**Comment by dputhier** [comment]
Fixed in cd2bda89901d8d7de926148c6df8260bc7640393
