### ISSUE TITLE
Various warnings and duplicate symbols

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#84]
Hi,
I'm trying to make compilation compatible for both py2k and Py3k. When running installation with py3k I get several warnings and a 'duplicate symbols' error. 
Any idea ?

    running install
    running bdist_egg
    running egg_info
    writing pygtftk.egg-info/PKG-INFO
    writing dependency_links to pygtftk.egg-info/dependency_links.txt
    writing requirements to pygtftk.egg-info/requires.txt
    writing top-level names to pygtftk.egg-info/top_level.txt
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    package init file 'pygtftk/data/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/data/simple_02/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/data/simple_03/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/data/simple_05/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/data/mini_real/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/data/control_list/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/src/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/src/libgtftk/__init__.py' not found (or not a regular file)
    package init file 'pygtftk/src/libgtftk/command/__init__.py' not found (or not a regular file)
    reading manifest file 'pygtftk.egg-info/SOURCES.txt'
    writing manifest file 'pygtftk.egg-info/SOURCES.txt'
    installing library code to build/bdist.macosx-10.6-intel/egg
    running install_lib
    running build_py
    copying pygtftk/version.py -> build/lib.macosx-10.6-intel-3.6/pygtftk
    running build_ext
    building 'pygtftk/lib/libgtftk' extension
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/add_attr_column.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attr_column.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/add_attr_to_pos.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attr_to_pos.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/add_attributes.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attributes.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/add_exon_number.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/add_prefix.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_prefix.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/clear_indexes.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/clear_indexes.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/convert_to_ensembl.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/convert_to_ensembl.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/del_attributes.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/del_attributes.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/extract_data.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/extract_data.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/free_gtf_data.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/free_gtf_data.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/free_raw_data.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/free_raw_data.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/get_list.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/get_list.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/get_sequences.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/get_sequences.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    pygtftk/src/libgtftk/command/get_sequences.c:206:52: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                    while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:213:19: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                    maxLineSize = MAX(maxLineSize, strlen(buffer));
                                                  ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
    pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
    #define MAX(x, y) (x > y ? x : y)
                       ~ ^ ~
    pygtftk/src/libgtftk/command/get_sequences.c:231:52: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                    while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:241:53: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                            while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:247:20: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                            maxLineSize = MAX(maxLineSize, strlen(buffer));
                                                          ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
    pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
    #define MAX(x, y) (x > y ? x : y)
                       ~ ^ ~
    pygtftk/src/libgtftk/command/get_sequences.c:267:16: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
            for (k = 0; k < strlen(seq->sequence); k += 60)
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~
    6 warnings generated.
    pygtftk/src/libgtftk/command/get_sequences.c:206:52: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                    while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:213:19: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                    maxLineSize = MAX(maxLineSize, strlen(buffer));
                                                  ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
    pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
    #define MAX(x, y) (x > y ? x : y)
                       ~ ^ ~
    pygtftk/src/libgtftk/command/get_sequences.c:231:52: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                    while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:241:53: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
                            while ((n = getline(&buffer, &size, fasta_file)) != -1) {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
    pygtftk/src/libgtftk/command/get_sequences.c:247:20: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                                            maxLineSize = MAX(maxLineSize, strlen(buffer));
                                                          ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
    pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
    #define MAX(x, y) (x > y ? x : y)
                       ~ ^ ~
    pygtftk/src/libgtftk/command/get_sequences.c:267:16: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
            for (k = 0; k < strlen(seq->sequence); k += 60)
                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~
    6 warnings generated.
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/load_gtf.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/load_gtf.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/merge_attr.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/merge_attr.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_by_genomic_location.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_genomic_location.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_by_key.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_key.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_by_number_of_exon.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_number_of_exon.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_by_positions.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_positions.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_by_transcript_size.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_transcript_size.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/command/select_transcript.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_transcript.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/column.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/column.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/gtf_reader.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/gtf_reader.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ipygtftk/src/libgtftk -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pygtftk/src/libgtftk/libgtftk.c -o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/libgtftk.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -MMD -MP -fmessage-length=0 -shared
    clang-6.0: warning: argument unused during compilation: '-shared' [-Wunused-command-line-argument]
    /Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang -dynamiclib -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attr_column.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attr_to_pos.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_attributes.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_prefix.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/clear_indexes.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/convert_to_ensembl.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/del_attributes.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/extract_data.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/free_gtf_data.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/free_raw_data.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/get_list.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/get_sequences.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/load_gtf.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/merge_attr.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_genomic_location.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_key.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_number_of_exon.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_positions.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_transcript_size.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_transcript.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/column.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/gtf_reader.o build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/libgtftk.o -L/usr/lib -lz -o build/lib.macosx-10.6-intel-3.6/pygtftk/lib/libgtftk.cpython-36m-darwin.so
    duplicate symbol _gtf_d in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/convert_to_ensembl.o
    duplicate symbol _gtf_d in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_number_of_exon.o
    duplicate symbol _tid_index in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/convert_to_ensembl.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_transcript.o
    duplicate symbol _row_list in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_number_of_exon.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_transcript.o
    duplicate symbol _gtf_d in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_transcript.o
    duplicate symbol _row_list in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_number_of_exon.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_transcript_size.o
    duplicate symbol _gtf_d in:
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/add_exon_number.o
        build/temp.macosx-10.6-intel-3.6/pygtftk/src/libgtftk/command/select_by_transcript_size.o
    ld: 7 duplicate symbols for architecture i386
    clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/Users/puthier/miniconda2/envs/pygtftk_08_2018b/bin/clang' failed with exit status 1

**Comment by dputhier** [comment]
The duplicate symbol is fixed with '-fcommon'. The warnings remain.

**Comment by fafa13** [comment]
I just did a push to fix a minor bug in load_gtf and to put all global variables in a separate source file (globals.c). That should fix the bug of duplicate symbols, without '-fcommon'
Let me know if it works !

**Comment by dputhier** [comment]
It seems the system complains about '_all_rows' (Symbol not found).

	$ gtftk -h
	    |--- 13:43-WARNING : Failed to load plugin :/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/plugins/5p_3p_coords.py
	cannot load library '/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so': dlopen(/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so, 2): Symbol not found: _all_rows
	  Referenced from: /Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so
	  Expected in: flat namespace
	 in /Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so'
	    |--- 13:43-WARNING : Failed to load plugin :/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/plugins/add_exon_nb.py
	cannot load library '/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so': dlopen(/Users/puthier/miniconda3/envs/pygtftk_05_09_2018_py2k/lib/python2.7/site-packages/pygtftk-0.9.1.dev0+6db3-py2.7-macosx-10.9-x86_64.egg/pygtftk/lib/libgtftk.so, 2): Symbol not found: _all_rows

**Comment by dputhier** [comment]
Available in branch libgtftk_80e51f3d15ba9dac278528e3dbe474792f5457cd.

**Comment by dputhier** [comment]
Updated libgtftk_80e51f3d15ba9dac278528e3dbe474792f5457cd (forgot to commit)

**Comment by fafa13** [comment]
Did you add the new file "globals.c" in the compilation ?
