### ISSUE TITLE
Warnings upon compilation

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#85]
We still have some warnings upon package installation (with Python 3):

	pygtftk/src/libgtftk/command/get_sequences.c:213:19: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
	                                maxLineSize = MAX(maxLineSize, strlen(buffer));
	                                              ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
	pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
	#define MAX(x, y) (x > y ? x : y)
	                   ~ ^ ~
	pygtftk/src/libgtftk/command/get_sequences.c:247:20: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
	                                        maxLineSize = MAX(maxLineSize, strlen(buffer));
	                                                      ^   ~~~~~~~~~~~  ~~~~~~~~~~~~~~
	pygtftk/src/libgtftk/libgtftk.h:54:22: note: expanded from macro 'MAX'
	#define MAX(x, y) (x > y ? x : y)
	                   ~ ^ ~
	pygtftk/src/libgtftk/command/get_sequences.c:269:16: warning: comparison of integers of different signs: 'unsigned int' and 'int' [-Wsign-compare]
	        for (k = 0; k < seq->features->nb; k++) {
	                    ~ ^ ~~~~~~~~~~~~~~~~~
	3 warnings generated.

**Comment by fafa13** [comment]
I have pushed the fixes (in develop).

**Comment by dputhier** [comment]
Fixed in cd2bda89901d8d7de926148c6df8260bc7640393
