### ISSUE TITLE
Warning during installation under docker image

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#86]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ipygtftk/src/libgtftk -I/usr/include/python3.5m -c pygtftk/src/libgtftk/command/convert_to_ensembl.c -o build/temp.linux-x86_64-3.5/pygtftk/src/libgtftk/command/convert_to_ensembl.o -Ipygtftk/src/libgtftk -O3 -Wall -fPIC -fcommon -MMD -MP -fmessage-length=0
			pygtftk/src/libgtftk/command/convert_to_ensembl.c: In function ‘action_gene’:
			pygtftk/src/libgtftk/command/convert_to_ensembl.c:189:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
			     asprintf(&(g_row->field[3]), "%d", start);
			     ^
			pygtftk/src/libgtftk/command/convert_to_ensembl.c:190:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
			     asprintf(&(g_row->field[4]), "%d", end);
			     ^
			pygtftk/src/libgtftk/command/convert_to_ensembl.c: In function ‘action_transcript’:
			pygtftk/src/libgtftk/command/convert_to_ensembl.c:98:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
			     asprintf(&(tr_row->field[3]), "%d", start);
			     ^
			pygtftk/src/libgtftk/command/convert_to_ensembl.c:99:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
			     asprintf(&(tr_row->field[4]), "%d", end);

**Comment by fafa13** [comment]
I pushed some fixes for that.

**Comment by dputhier** [comment]
fixed in cd2bda89901d8d7de926148c6df8260bc7640393
