### ISSUE TITLE
get_sequence. Problem with rev-comp (critical...). Sequence truncated.

### ISSUE THREAD

**Issue by dputhier** [dputhier/libgtftk#89]
We have an issue with get_sequence. This was not highlighted by tests that, in this case, use short artificial transcripts. 
[ENST00000496905.txt](https://github.com/dputhier/libgtftk/files/2577736/ENST00000496905.txt)
This one is critical. The problem arise with reverse complement. The example gtf file is enclosed (as a txt file).

		from cffi import FFI
		from pygtftk.Line import FastaSequence
		from pygtftk.gtf_interface import GTF

		def native_str(x):
		    return bytes(x.encode())

		ffi = FFI()

		## hg38 chromosome 1
		genome_fa = "/Users/puthier/Downloads/chr1.fa"
		a_file = "/tmp/ENST00000496905.gtf"
		a_gtf = GTF(a_file)
		a_fa = a_gtf.get_sequences(genome_fa, rev_comp=True)

		## No intron no rev-comp
		gs = a_gtf._dll.get_sequences(a_gtf._data, native_str(genome_fa), 0, 0)
		# 608, the expected length of the transcript
		len(ffi.string(gs.sequence[0].sequence)) 

		## But with rev_comp we have a big issue
		gs = a_gtf._dll.get_sequences(a_gtf._data, native_str(genome_fa), 0, 1)
		len(ffi.string(gs.sequence[0].sequence)) # 9 !!!!

**Comment by dputhier** [comment]
I'm providing an additional example to try to demonstrate that the error lies somewhere on the C shore. Here I'm not using too much of Python object, trying to pass directly args to the dll.


	from cffi import FFI
	from pygtftk.Line import FastaSequence
	from pygtftk.gtf_interface import GTF


	def native_str(x):
	    return bytes(x.encode())

	ffi = FFI()



	## hg38 chromosome 1
	genome_fa = "pygtftk/chr1.fa"
	a_file = "pygtftk/ENST00000496905.gtf"
	a_gtf = GTF(a_file)


	## No intron no rev-comp
	gs = a_gtf._dll.get_sequences(a_gtf._data, native_str(genome_fa), 0, 0)
	print(ffi.string(gs.sequence[0].sequence).decode())

	## But with rev_comp we have a big issue
	print("----------")
	gs = a_gtf._dll.get_sequences(a_gtf._data, native_str(genome_fa), 0, 1)
	print(ffi.string(gs.sequence[0].sequence).decode())

**Comment by dputhier** [comment]
I have edited the last example.

**Comment by dputhier** [comment]
The error is persisting when using a full genome with all chr instead of only chr1.

**Comment by dputhier** [comment]
It seems that most of the time impacted transcript are on minus strand.

**Comment by fafa13** [comment]
The pb with reverse complement sequences is reproducible with the C library. This option was intended to get minus strand genes in the right way, that is 5' -> 3'.  So, only minus strand genes are impacted.

**Comment by fafa13** [comment]
FIXED !!! and pushed !!!

**Comment by dputhier** [comment]
Yes everything seems OK now. Some test were failing due to coordinate changes in ensembl between the last version (used to get the expected sequence) and the version used for constructing the mini_real dataset. 
You should create a new release with this fix

     git checkout develop
     git hf release start x.x.x
     # some additional modif if needed
     git hf release finish x.x.x
     # go to the release page of libgtftk project under github. Draft a new release with a novel fish :)
