### ISSUE TITLE
select_transcript

### ISSUE THREAD

**Issue by fafa13** [dputhier/libgtftk#9]
A new function is available :

GTF_DATA ***select_transcript**(GTF_DATA *gtf_data, int type)

This function replace : 
- select_shortest_transcript
- select_longest_transcript
- select_5p_transcript

The type argument is :
- 0 for select_shortest_transcript
- 1 for select_longest_transcript
- 2 for select_5p_transcript

select_shortest_transcript and select_longest_transcript get, for each gene, the shortest and longest transcript. The size of a transcript is the sum of the sizes of his exons.

select_5p_transcript gets, for each gene, the most 5' transcript. The strand of the gene is taken into account.

This function works at the gene level, so the "gene" rows are returned in the results.

**Comment by dputhier** [comment]
Christmas time ! Will interface that asap.

**Comment by dputhier** [comment]
A remark and a question:

- First, given the fact that one will return selected transcripts from a gene, the genomic boundaries for that gene could differ from that displayed by its associated transcripts. We may keep them in the C implementation to let the developper decide whether he wants or not to consider them. On my side, I can just decided to delete them by default in the command line version (by piping with a select_by_key("feature", "gene", not). This could then simply become an argument in the command line version.

- Second. We are talking about the mature RNA length ? I guess.

**Comment by dputhier** [comment]
Note that to my knowledge, select_by_nb_exon won't return gene lines.

**Comment by fafa13** [comment]
Yes, I forget to precise this point. Maybe we should have a unique 
policy for functions that select transcripts :
- select_transcript (shortest, longest, most 5')
- select_by_number_of_exon
- select_by_transcript_size

The "natural" behavior of these functions is to NOT return gene lines. 
So, I have to do extra work to get the gene lines.

Do you think I have to add a parameter for the user to specify if he 
wants gene lines in the results of these functions ?

**Comment by fafa13** [comment]
Yes, it is the mature RNA length.

**Comment by dputhier** [comment]
Maybe I'm answering a little bit late. I don't think there is a real need to make it possible to keep the gene line if one decide of this policy.
